description: Exceptions File for vet
exceptions:
  - ecosystem: cargo
    expires: "2026-06-01T00:00:00Z"
    name: "unicase"
    version: "2.8.1"
  - ecosystem: go
    expires: "2026-06-01T00:00:00Z"
    name: "github.com/google/uuid"
    version: "1.5.0"
